---
name: transformator
version: 0.1.4
description: event-based server for jade-lang, minify and transformers
keywords:
  - jade
  - minify
  - transformers
  - coffeescript
homepage: https://github.com/zurborg/transformator
bugs:
  url: https://github.com/zurborg/transformator/issues
license: ISC
author: David Zurborg <post@david-zurb.org>
files: ~
main: lib/transformator.js
repository:
  type: git
  url: https://github.com/zurborg/transformator.git
dependencies:
  sync: >=0.2.5
  jade: >=1.7.0
  cbor: >=0.3.0
  minify: >=1.3.0
  transformers: >=3.1.0
engines:
  node: ~0.12
bin: ./bin/transformator
